config/routes.rb
Rails.application.routes.draw do

  get 'books/index'
  get 'books/new'
  post 'books', to: 'books#create'

  put 'books/:id', to: 'books#update'
  patch 'books/:id', to: 'books#update'

  # /books/1/edit
  get 'books/:id/edit', to: 'books#edit', as: 'books_edit'
  # /books/1
  get 'books/:id', to: 'books#show', as: 'book'

  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    enum status: %i[in_shell lended]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_book, only: %i[show edit update]

    def index
        @books = Book.all
    end

    def show
    end

    def new
        @book = Book.new
        @statuses = Book.statuses.keys
    end

    def create
        @book = Book.new(book_params)

        respond_to do |format|
            if @book.save
                format.html { redirect_to book_path(@book.id), notice: 'El libro fue creado exitosamente' }
            else
                format.html { render :new }
            end
        end
    end

    def edit
        @statuses = Book.statuses.keys
    end

    def update
    end

    private

    def set_book
        @book = Book.find(params[:id])
    end

    def book_params
        params.require(:book).permit(:title, :status, :author, :borrowed_at, :returned_at)
    end
end

 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<div class="container">
<%= form_with(model: book) do |form| %>

    <div class="form-group form-check">
        <%= form.label :title, class: 'form-check-label' %>
        <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group form-check">
        <%= form.label :author, class: 'form-check-label' %>
        <%= form.text_field :author, class: 'form-control' %>
    </div>

    <div class="form-group form-check">
        <%= form.label :status %>
        <%= form.select :status, @statuses, {}, class: 'form-control' %>
    </div>

    <%= form.submit %>
<% end %>
</div> 

app/views/books/edit.html.erb
div class="container">
    <h1>Editar Libro</h1>

    <%= render 'form', book: @book %>
</div> 

app/views/books/index.html.erb
<div class="container">
    <h1>Books</h1>

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Titulo</th>
      <th scope="col">Autor</th>
      <th scope="col">Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <th><%= book.id %></th>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.status %></td>
        <td class="text-center">
          <%=link_to 'Detalle', book_path(book.id)%>
        </td>
      <td class="text-center">
          <%= link_to 'Editar', books_edit_path(book.id) %>
      </td>
      <td class="text-center">
           <%= link_to 'Destroy', '#', class: 'text-danger' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>      
</div>

app/views/books/new.html.erb
<div class="container">
    <h1>Nuevo Libro</h1>

    <%= render 'form', book: @book %>
</div> 

app/views/books/show.html.erb
<div class="container">
    <h1><strong><%= @book.title %></strong></h1>
    <p>
        <strong>Autor:</strong>
        <%= @book.author %>
    </p>
    <p>
        <strong>Estado:</strong>
        <%= @book.status %>
    </p>
    <p>
        <strong>Prestado en:</strong>
        <%= @book.borrowed_at %>
    </p>
    <p>
        <strong>Devuelto en:</strong>
        <%= @book.returned_at %>
    </p>

    <%= link_to 'Volver', root_path %>
</div> 

app/views/layouts/application.html.erb
<div class="container">
    <!DOCTYPE html>
    <html>
      <head>
        <title>MiBiblioteca</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

          <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
          <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      </head>

      <body>
        
          <%= yield %>
        
      </body>
    </html>
</div>